# Generated by Django 3.2.3 on 2021-05-25 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='contact',
            new_name='content',
        ),
    ]
